<a href="https://colab.research.google.com/github/soujanya-vattikolla/Data-Analysis-for-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Basic Numpy Arrays**

In [2]:
# creating a array

array_a = np.array([1,2,3,4,5])
array_a

array([1, 2, 3, 4, 5])

In [3]:
# accessing the values in the numpy array

print(array_a[1])
print(array_a[3])

2
4


In [4]:
# slicing the array

print(array_a[0:])

[1 2 3 4 5]


In [5]:
# slicing the array with negative index
print(array_a[2:-1])

[3 4]


In [6]:
# creating a array with decimal numbers
array_b = np.array([0., 0.5, 1., 1.5, 3])
array_b

array([0. , 0.5, 1. , 1.5, 3. ])

In [7]:
# multiindexing to access the values
array_b[ [0,2,-1] ]

array([0., 1., 3.])

**Array Types**

In [8]:
# to check data type of the array
array_a.dtype

dtype('int64')

In [9]:
array_b.dtype

dtype('float64')

In [10]:
# we can assign the datatype while declaring the array
array_c = np.array([5,6,7,10], dtype=np.int8)
array_c

array([ 5,  6,  7, 10], dtype=int8)

**Dimensions and shapes**

In [11]:
# creating a multidimensional arrays
# creating a 2 dimensional array

twodimarray = np.array([ [7,8,9],
                       [10,11,12]])
twodimarray

array([[ 7,  8,  9],
       [10, 11, 12]])

In [12]:
# to know the shape of the multidimensional arrays
# number of rows and number of columns
twodimarray.shape


(2, 3)

In [13]:
# size of the multidimensional arrays
twodimarray.size

6

In [14]:
# creating a 3 Dimensional array
threedimarray = np.array([
                         [ [5,7,8],
                          [1,4,5],
                          ],
                        [  [10,20,30],
                          [40,50,60],
                        ],
                        ])

In [15]:
threedimarray 


array([[[ 5,  7,  8],
        [ 1,  4,  5]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [16]:
# shape of 3 dimensional array

threedimarray.shape

(2, 2, 3)

In [17]:
# size of 3 dimensional array

threedimarray.size


12

**Indexing and Slicing of Matrices**

In [18]:
# Square matrix
matrix_index =  np.array([
                          #.   0. 1. 2
                              [1, 2, 3], # 0
                              [4, 5, 6], # 1
                              [7, 8, 9]  # 2
])

In [19]:
matrix_index[2]

array([7, 8, 9])

In [20]:
# we are acessing the value at the 2nd row and 1st column
matrix_index[2][1]

8

In [21]:
# slicing the matrix
matrix_slice = np.array([
                         [10,20,30],
                         [40,50,70],
                         [80,90,100]
                         ])

In [22]:
# accessing the elements from 0 to 2nd row
matrix_slice[:2]

array([[10, 20, 30],
       [40, 50, 70]])

In [23]:
# accessing the elements from 0 and 1st column
matrix_slice[:,:2]

array([[10, 20],
       [40, 50],
       [80, 90]])

In [24]:
matrix_assign = np.array([
                          [7,4,1],
                          [8,5,2],
                          [9,6,3]
])

In [25]:
# assigning new values to 2nd row
matrix_assign[1] = np.array([20,20,20])
matrix_assign

array([[ 7,  4,  1],
       [20, 20, 20],
       [ 9,  6,  3]])

In [26]:
# assigning new values to 1st row
matrix_assign[0] = 100
matrix_assign

array([[100, 100, 100],
       [ 20,  20,  20],
       [  9,   6,   3]])

**Statistics Summary**

In [27]:
stats_a = np.array([50,60,70])
stats_a

array([50, 60, 70])

In [28]:
# mean of the array
stats_a.mean()

60.0

In [29]:
# sum of the array
stats_a.sum()

180

In [30]:
stats_b = np.array([
                    [7,8,9],
                    [4,5,6],
                    [1,2,3]
])

In [31]:
# sum of the values along the row elements
stats_b.sum(axis=0)

array([12, 15, 18])

In [32]:
# mean of the values along the column elements
stats_b.mean(axis=1)

array([8., 5., 2.])

**Broadcasting and Vectorized operations**

In [33]:
# creating a array with range of 5
broadcast_array = np.arange(5)
broadcast_array

array([0, 1, 2, 3, 4])

In [34]:
# multiplying array by 100
broadcast_array*100

array([  0, 100, 200, 300, 400])

In [35]:
# adding 20 to the array
broadcast_array+= 20
broadcast_array

array([20, 21, 22, 23, 24])

In [36]:
broadcast_array_a = np.arange(4)
broadcast_array_a

array([0, 1, 2, 3])

In [37]:
broadcast_array_b = np.array([20,30,40,50])
broadcast_array_b

array([20, 30, 40, 50])

In [38]:
# adding two arrays
broadcast_array_a + broadcast_array_b

array([20, 31, 42, 53])

**Boolean arrays**

In [39]:
boolean_array = np.arange(4)
boolean_array

array([0, 1, 2, 3])

In [40]:
# check the elements >= 2
boolean_array>=2


array([False, False,  True,  True])

In [41]:
boolean_array.mean()

1.5

In [42]:
# check the elements > mean(1.5)
boolean_array[boolean_array > boolean_array.mean()]

array([2, 3])

In [43]:
# creating a array with random numbers
boolean_array_a = np.random.randint(50,size=(2,2))
boolean_array_a

array([[ 4,  7],
       [12, 34]])

In [44]:
# check the elements >= 20 in the array
boolean_array_a >= 20

array([[False, False],
       [False,  True]])

**Linear Algebra**

In [45]:
linear_array_a = np.array([
                           [7,4,1],
                           [8,5,2],
                           [9,6,3]
])

In [46]:
linear_array_b = np.array([
                           [6,1],
                           [8,2],
                           [9,1]
                           ])

In [47]:
# Transposing the matrix
linear_array_b.T

array([[6, 8, 9],
       [1, 2, 1]])

**Size of objects in Memory**

In [48]:
import sys

In [49]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [50]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [51]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [52]:
# Lists are even larger
# A one-element list
sys.getsizeof([1])

80

**Numpy functions**

In [53]:
# random

rand_array = np.random.random(size=2)
rand_array

array([0.22884731, 0.42708688])

In [54]:
#  reshape

reshape_array = np.arange(10).reshape(2, 5)
reshape_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
# linspace

linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [56]:
# zeros
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
# Return the identity array.
# The identity array is a square array with ones on the main diagonal.

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])