<a href="https://colab.research.google.com/github/soujanya-vattikolla/Data-Analysis-for-Python/blob/main/Numpy%20exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy exercises**

In [1]:
# Import the numpy package under the name np
import numpy as np

In [2]:
# Print the numpy version and the configuration
print(np.__version__)

1.21.5


**Array creation**

In [3]:
# Create a numpy array of size 10, filled with zeros.

zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Create a numpy array with values ranging from 10 to 49

arange_array = np.arange(10,50)
arange_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# Create a numpy matrix of 2*2 integers, filled with ones.

ones_array = np.ones([2,2],dtype=int)
ones_array

array([[1, 1],
       [1, 1]])

In [6]:
# Create a numpy matrix of 3*2 float numbers, filled with ones.

float_array = np.ones([3,2], dtype=float)
float_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

X_array = np.arange(4,dtype=int)
print(X_array)

new_array = np.ones_like(X_array)
print(new_array)

[0 1 2 3]
[1 1 1 1]


In [8]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

X_array = np.arange(6)
print(X_array)

new_array = np.zeros_like(X_array)
print(new_array)

[0 1 2 3 4 5]
[0 0 0 0 0 0]


In [9]:
# Create a numpy matrix of 4*4 integers, filled with fives.

five_array = np.ones([4,4],dtype=int)*5
five_array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.


X_array = np.array([[1,3],[5,2]],dtype=int)
print(X_array)

seven_array = np.ones_like(X_array)*7
print(seven_array)

[[1 3]
 [5 2]]
[[7 7]
 [7 7]]


In [11]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

identity_array = np.identity(3)
identity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.

rand_array = np.random.randint(10,size=3)
rand_array

array([7, 4, 4])

In [13]:
# Create a 3*3*3 numpy matrix, filled with random float values.

rand_val = np.random.randn(3,3,3)
rand_val

array([[[ 0.99155518,  1.22301551,  0.82906891],
        [ 0.13213728, -0.26592251, -0.89670693],
        [-1.00206734, -0.77761068, -0.31378627]],

       [[-1.89872939,  1.12976989,  0.10268614],
        [ 1.80758086,  0.44326234, -1.27832333],
        [ 0.41619805,  0.08016681, -0.64539025]],

       [[ 0.62138866,  0.33252679,  0.18252713],
        [-0.45272538, -0.58316208,  0.22615383],
        [-0.11502651,  0.27600261, -1.15860778]]])

In [14]:
# Create a numpy array with the odd numbers between 1 to 10

odd_array = np.arange(1,10,2)
odd_array


array([1, 3, 5, 7, 9])

In [15]:
# Create a numpy array with numbers from 1 to 10, in descending order.

desc_array = np.arange(1,11)[::-1]
desc_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

range_array = np.arange(9).reshape(3,3)
range_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# Show the memory size of the given Z numpy matrix

Z = np.ones(3,dtype=int)
print(Z)
print(Z.size)
print(Z.itemsize)
print("%d bytes"%(Z.size * Z.itemsize))

[1 1 1]
3
8
24 bytes


**Array indexation**

In [18]:
# Given the X numpy matrix, show the first row elements

firstrow_X = np.array([
              [1,2,3,4],
              [5,6,7,8],
              [9,0,-1,-2]
])

firstrow_X[0]

array([1, 2, 3, 4])

In [19]:
# Given the X numpy matrix, show the first element on first row

firstelemnt_X = np.array([
              [-1,2,3,4],
              [5,6,7,8],
              [9,0,-1,-2]
])

firstelemnt_X[0][0]

-1

In [20]:
# Given the X numpy matrix, show the last element on last row

lastelemnt_X = np.array([
              [1,12,13,14],
              [5,6,7,8],
              [9,0,-1,-2]
])

lastelemnt_X [2][3]

-2

In [21]:
# Given the X numpy matrix, show the middle row elements

middle_X = np.array([
              [1,2,3,4],
              [5,16,17,8],
              [19,0,-1,-2]
])

middle_X[1:-1, 1:-1]

array([[16, 17]])

In [22]:
# Given the X numpy matrix, show the last two elements on the last two rows

lasttwo_X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

lasttwo_X[2:,2:]

array([[11, 12],
       [15, 16]])

**Array manipulation**

In [23]:
# Convert the given integer numpy array to float

int_array = np.arange(5)
print(int_array)

float_array = np.array(int_array,float)
print(float_array)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [24]:
# Given the X numpy array, set the fifth element equal to 1

X_fiftharray = np.array([10,20,30,40,50,60])
X_fiftharray

X_fiftharray[4] = 1

print(X_fiftharray)

[10 20 30 40  1 60]


In [25]:
# Given the X numpy matrix, change the last item on the last row with a 0

X_lastarray = np.array ([
                     [1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12]
])

X_lastarray[2][3] = 0

X_lastarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  0]])

**Boolean arrays (also called masks)**

In [26]:
# Given the X numpy array, make a mask showing negative elements

negative_array = np.array([-1,2,3,-9,-8,-7])

mask = negative_array <=0
mask

array([ True, False, False,  True,  True,  True])

In [27]:
# Given the X numpy array, get numbers equal to 2 or 10

X_equalarray = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = (X_equalarray == 2)| (X_equalarray == 10)
mask

array([False,  True, False, False, False, False, False, False, False,
        True])

**Logic functions**

In [28]:
# Given the X numpy array, return True if any of its elements is zero

any0_array = np.array([1,2,0,3,4,0,8,90])
any0_array.any()

True

**Summary statistics**

In [29]:
# Given the X numpy matrix, show the sum of its columns

sum_array = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

sum_array.sum(axis=0)

array([28, 32, 36, 40])

In [30]:
# Given the X numpy array, show the max value of its elements

maxval_array = np.array([10,8,70,40,20,9,6,4])
maxval_array.max()

70